name: my_courses_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.0
  google_fonts: ^6.1.0
  webview_flutter: ^4.4.2
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
